name: 'run-on-container'
description: 'Run on container'
inputs:
  run:
    description: Commands to run
    required: true
  image:
    description: Image of container
    required: true
  platform:
    description: Platform of container
    required: false
    default: 'linux/amd64'
  args:
    description: Additional args for `docker run`
    required: false
  shell:
    description: Shell
    required: false
    default: 'sh'
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: ${{ inputs.platform }}
    - name: Run command on container
      run: |
        tmpfile=$(mktemp)
        echo 'set -ex' > $tmpfile
        echo 'cd /work' >> $tmpfile
        cat <<"EOF" >> $tmpfile
        ${{ inputs.run }}
        EOF
        echo "::group::Commands to run on container"
        cat $tmpfile
        echo "::endgroup::"
        docker run -v ${{ github.workspace }}:/work -v $tmpfile:/__run.sh -w /work --platform ${{ inputs.platform }} --env WORKSPACE=/work ${{ inputs.args }} ${{ inputs.image }} ${{ inputs.shell }} /__run.sh
        rm $tmpfile
      shell: bash
