name: 'run-on-container'
description: 'Run on container'
inputs:
  run:
    description: Command
    required: true
  image:
    description: Container image
    required: true
  platform:
    description: Platform
    required: false
    default: 'linux/amd64'
  shell:
    description: Shell
    required: false
    default: 'sh'    
runs:
  using: "composite"
  steps:
    - run: |
        echo ${{ inputs.run }} > ${{ github.workspace }}/___run.sh
        docker run -v ${{ github.workspace }}:/work -w /work --platform ${{ inputs.platform }} ${{ inputs.image }} ${{ inputs.shell }} ___run.sh
        rm ${{ github.workspace }}/___run.sh
      shell: bash
